# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 372f494586a33b06c699432a55e72275704de9d3b600825cfe55a4388c2520e8717e47118274e579dab3a4c5b2501cb698c4515a43ecc12c138db37045272da2

test:
  secret_key_base: 0004ed32d8e04d90cf626da04b39d732da07590b2bd00b4e6a2fec47e2615b108dd0900c438bcd81522b1b0ff4073ede4eecef59430b85d361f1308cc29b084a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
